# Generated by Django 4.1.7 on 2023-03-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clents_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database1',
            new_name='Database',
        ),
    ]
